# Page settings
baseurl = "localhost:1313"
title = "Taggr for OSX"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""
  # Navigation
  [params.navigation]
    brand = "Taggr"
    home = "Home"
    work = "Screenshots"
    testimonials = "Testimonials"
    services = "Features"
    about = "About"
    contact = "Download"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Organize the photos you love."
    subtitle = 'The only fully automatic, intelligent photo management system for OSX. Forever free. Coded in Python by <a href="http://naveenarun.github.io">Naveen Arun</a>, Anthony Varelas, and Ying Wang at <a href="http://hacktech.io" title="Hacktech">Hacktech 2017</a>.'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Focus on Content."
    description = "As a content creator, you are doubly tasked with producing creative multimedia and organizing it. With Taggr, you can leave the latter and focus on more important creative tasks."
    url = "#fh5co-work"
    button = "Screenshots"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Optimize your Workflow."
    description = "Creative work requires fast results. Taggr pipelines directly into Spotlight, allowing you to quickly locate photos in just a few keystrokes. No more manual searching!"
    url = "#fh5co-services"
    button = "Features"
    icon = "icon-screen-desktop"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Leave Tagging to Us."
    description = "Integration with Microsoft Cognitive Services allows Taggr to categorizes you photos in a snap. Intuitive tags allow you to find hard-to-locate pictures by description alone."
    url = "#fh5co-contact"
    button = "Download"
    icon = "icon-camera"
    img = "img_10.jpg"





  # Work section
  [params.work]
    enable = true
    title = "Screenshots"
    description = "Taggr uses artificial intelligence to create smart, descriptive tags for your photos."
    footertext = '** Demo images created with Python 2.7 and Tk on OSX Yosemite 10.10.2'

    [[params.work.row]]
      img = "penguin_small.png"
      alt = "Photo and Corresponding Tags"
      title = "Tagged Photo"
      subtitle = "Penguins"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Design"

    [[params.work.row]]
      img = "finder.png"
      alt = "Spotlight demo"
      title = "Spotlight Integration"
      subtitle = "Finder"


  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"
    



  # Services section
  [params.services]
    enable = true
    title = "Features"
    description = "Taggr's design makes it ideal for content creators."

    [[params.services.item]]
      title = "Get tags from the cloud"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-cloud-download"

    [[params.services.item]]
      title = "Quickly search for relevant photos"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-layers2"
    [[params.services.item]]
      title = "Work across all your photos"
      description = "Doesn't matter large or small (downsampled); jpg bmp gif png"
      icon = "icon-camera"

      [[params.services.item]]
      title = "Automate your work"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"      
      icon = "icon-loop"

  # About section
  [params.about]
    enable = true
    title = "About"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.about.item]]
      name = "Naveen Arun"
      position = "ChemE, Junior"
      description = "Caltech undergrad passionate about teaching, research, and computing, with a bent for Python, C++, and JS."
      img = "person1.jpg"
      alt = "Person1"


    [[params.about.item]]
      name = "Ying Wang"
      position = "CS, Freshman"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Person2"

    [[params.about.item]]
      name = "Anthony Varelas"
      position = "ChemE, Sophomore"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
    

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = true
    title = "Download"
    description = "Download and installation instructions are available on <a href='http://github.com/naveenarun/hacktech_2017/'>Github</a>."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "1200 E California Blvd, <br> Pasadena, CA"],
        ["icon-envelope", "narunach [at] caltech.edu <br> "],
        ["icon-globe", '<a href="http://freehtml5.co/" target="_blank">freehtml5.co</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = false
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
